package com.tarantulapp.service.vendors.adapters;

import com.tarantulapp.entity.OfficialVendor;
import com.tarantulapp.service.vendors.sources.StrategicVendorRawListing;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.List;
import java.util.Locale;

@Component
public class MockStrategicPartnerListingAdapter implements StrategicPartnerListingAdapter {

    private final boolean enabled;

    public MockStrategicPartnerListingAdapter(
            @Value("${app.partner-sync.adapters.mock.enabled:true}") boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public boolean supports(OfficialVendor vendor) {
        if (!enabled || vendor == null || vendor.getSlug() == null) return false;
        String slug = vendor.getSlug().toLowerCase(Locale.ROOT);
        return slug.startsWith("mock-");
    }

    @Override
    public List<StrategicVendorRawListing> fetch(OfficialVendor vendor) {
        String slug = vendor.getSlug();
        return List.of(
                new StrategicVendorRawListing(
                        slug + "-001",
                        "Aphonopelma seemanni juvenile",
                        "Mock strategic inventory generated by adapter.",
                        "Aphonopelma seemanni",
                        new BigDecimal("149.90"),
                        "USD",
                        5,
                        "https://images.example.com/" + slug + "/aphonopelma.jpg",
                        "https://partner.example.com/" + slug + "/aphonopelma-seemanni",
                        vendor.getCountry(),
                        vendor.getState(),
                        vendor.getCity()
                ),
                new StrategicVendorRawListing(
                        slug + "-002",
                        "Tliltocatl vagans subadult",
                        "Mock strategic inventory generated by adapter.",
                        "Tliltocatl vagans",
                        new BigDecimal("119.50"),
                        "USD",
                        0,
                        "https://images.example.com/" + slug + "/tliltocatl.jpg",
                        "https://partner.example.com/" + slug + "/tliltocatl-vagans",
                        vendor.getCountry(),
                        vendor.getState(),
                        vendor.getCity()
                )
        );
    }

    @Override
    public String id() {
        return "mock";
    }
}
