ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_beta_tester BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS beta_cohort VARCHAR(80),
    ADD COLUMN IF NOT EXISTS beta_country VARCHAR(80),
    ADD COLUMN IF NOT EXISTS beta_experience_level VARCHAR(40);
