export const COUNTRY_OPTIONS = ['Mexico', 'United States', 'Canada']

export const STATES_BY_COUNTRY = {
  Mexico: [
    'CDMX',
    'Estado de Mexico',
    'Jalisco',
    'Nuevo Leon',
    'Puebla',
    'Guanajuato',
    'Queretaro',
    'Yucatan',
    'Sonora',
    'Quintana Roo',
  ],
  'United States': [
    'California',
    'Texas',
    'Florida',
    'New York',
    'Illinois',
    'Arizona',
    'Washington',
  ],
  Canada: [
    'Ontario',
    'Quebec',
    'British Columbia',
    'Alberta',
  ],
}

export const CITIES_BY_STATE = {
  CDMX: ['Ciudad de Mexico'],
  'Estado de Mexico': ['Naucalpan', 'Tlalnepantla', 'Ecatepec', 'Toluca'],
  Jalisco: ['Guadalajara', 'Zapopan', 'Tlaquepaque'],
  'Nuevo Leon': ['Monterrey', 'San Nicolas', 'Guadalupe'],
  Puebla: ['Puebla', 'Tehuacan'],
  Guanajuato: ['Leon', 'Irapuato', 'Celaya'],
  Queretaro: ['Queretaro', 'San Juan del Rio'],
  Yucatan: ['Merida'],
  Sonora: ['Hermosillo'],
  'Quintana Roo': ['Cancun', 'Playa del Carmen'],
  California: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco'],
  Texas: ['Houston', 'Dallas', 'Austin', 'San Antonio'],
  Florida: ['Miami', 'Orlando', 'Tampa'],
  'New York': ['New York City', 'Buffalo'],
  Arizona: ['Phoenix', 'Tucson'],
  Illinois: ['Chicago'],
  Washington: ['Seattle'],
  Ontario: ['Toronto', 'Ottawa', 'Mississauga'],
  Quebec: ['Montreal', 'Quebec City', 'Laval'],
  'British Columbia': ['Vancouver', 'Victoria', 'Surrey'],
  Alberta: ['Calgary', 'Edmonton'],
}
